### ISSUE TITLE
moveWeights.sh issues

### ISSUE THREAD

**Issue by bedna-KU** [kritiksoman/GIMP-ML#1]
First issue
`
mv: target 'CelebAMask-HQ/MaskGAN_demo/checkpoints/label2face_512p/' is not a directory
mv: target 'monodepth2/models/mono+stereo_640x192/' is not a directory
mv: cannot move 'weights/super_resolution/model_srresnet.pth' to 'pytorch-SRResNet/model/': Not a directory
`
Resolved with **mkdir pytorch-SRResNet/model**

Second issue
`
mv: target 'CelebAMask-HQ/MaskGAN_demo/checkpoints/label2face_512p/' is not a directory
mv: target 'monodepth2/models/mono+stereo_640x192/' is not a directory
`
Resolved with **mkdir -p mkdir monodepth2/models/mono+stereo_640x192**

Third issue
`
mv: target 'CelebAMask-HQ/MaskGAN_demo/checkpoints/label2face_512p/' is not a directory
`
Resolved with **mkdir -p CelebAMask-HQ/MaskGAN_demo/checkpoints/label2face_512p**

**Comment by kritiksoman** [comment]
@bedna-KU Thanks. moveWeights.sh has been updated.
