### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by pums974** [kritiksoman/GIMP-ML#15]
The super-resolution module crash with this error :

RuntimeError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 1.95 GiB total capacity; 955.34 MiB already allocated; 5.38 MiB free; 1.01 GiB reserved in total by PyTorch)

Maybe add the GPU memory requirement in the README

**Comment by kritiksoman** [comment]
Try Force CPU button.

**Comment by kritiksoman** [comment]
check now (set "Use as filter" to True)
