### ISSUE TITLE
MonoDepth resolution

### ISSUE THREAD

**Issue by tcharlss** [kritiksoman/GIMP-ML#18]
The MonoDepth filter is super handy, but it seems it operates at a very low resolution and then resize the new layer, making it quite blurry, and thus not so usable.

Could it be possible to add a parameter in order to increase its resolution?

**Comment by valgur** [comment]
You can try the implementation in my fork of GIMP-ML, which should work as expected: https://github.com/valgur/GIMP-ML-Hub

**Comment by tcharlss** [comment]
Thanks I will give it a try :)

**Comment by kritiksoman** [comment]
@tcharlss MiDas was originally by the authors on images of size 384 by 384.
