### ISSUE TITLE
deeplabv3 (Exec format error)

### ISSUE THREAD

**Issue by bedna-KU** [kritiksoman/GIMP-ML#2]
System: Linux antixbud 4.9.189-antix.1-amd64-smp #1 SMP PREEMPT Thu Aug 15 01:53:58 BST 2019 x86_64 GNU/Linux

$ gimp
gimp: /usr/lib/x86_64-linux-gnu/libbabl-0.1.so.0: no version information available (required by gimp)
gimp: /usr/lib/x86_64-linux-gnu/libbabl-0.1.so.0: no version information available (required by /usr/lib/libgimpwidgets-2.0.so.0)
gimp: /usr/lib/x86_64-linux-gnu/libbabl-0.1.so.0: no version information available (required by /usr/lib/libgimpcolor-2.0.so.0)
GIMP-Error: Unable to run plug-in "deeplabv3"
(/home/mario/bin/GIMP-ML/gimp-plugins/deeplabv3)

Failed to execute child process “/home/mario/bin/GIMP-ML/gimp-plugins/deeplabv3” (Exec format error)

gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
GIMP-Error: Unable to run plug-in "deeplabv3.py"
(/home/mario/bin/GIMP-ML/gimp-plugins/deeplabv3.py)

Failed to execute child process “/home/mario/bin/GIMP-ML/gimp-plugins/deeplabv3.py” (Exec format error)

gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error

**Comment by nortikin** [comment]
what format should be?

**Comment by bedna-KU** [comment]
@nortikin functional.

**Comment by nortikin** [comment]
@bedna-KU 
hope it will be solved one day and i can enjoy of GIMP ML on linux

**Comment by bedna-KU** [comment]
@nortikinMe too :)

**Comment by germanzhu** [comment]
only py file add executable
sudo apt install gimp-python

**Comment by nortikin** [comment]
issue solved in last comment. thank you.
please, add dependences in description for particular
