### ISSUE TITLE
"colorize..." is not there

### ISSUE THREAD

**Issue by datalot-369** [kritiksoman/GIMP-ML#21]
In the [official playlist of examples in YouTube](https://www.youtube.com/playlist?list=PLo9r5wFmpD5dLWTyo6NOiD6BJjhfEOM5t) is shown [how `colorize...` plugin acts](https://www.youtube.com/watch?v=HVwISLRow_0&list=PLo9r5wFmpD5dLWTyo6NOiD6BJjhfEOM5t&index=10&t=0s), but `colorize...` is not there, even in the main README.MD [Tools Licences Table](https://github.com/kritiksoman/GIMP-ML#license) it's not shown.

I don't know if this is the right place to say it, but at least one "DISCLAIMER" on that video's description would be good enough. By the way, this issue is to get a "technical" explanation instead of an "After version X is no longer available".

**Comment by kritiksoman** [comment]
it has been replaced with "deepcolor" as Local Hints Network had better control over coloring in image for user.

**Comment by datalot-369** [comment]
Could you attach an example of coloring with the new way for the same image used in the original tutorial?

**Comment by kritiksoman** [comment]
Example video of coloring with new method: [video link](https://www.youtube.com/watch?v=4YpTa-gqEIw)

Result on the requested image: [link](https://www.instagram.com/p/CE_-be1D8qj/)
This was done without using local points (Original image and color mask were set to the same layer containing the image).

**Comment by datalot-369** [comment]
Closed as resolved with satisfactory answers.
