### ISSUE TITLE
Please let us choose to work with CPU when CUDA is detected.

### ISSUE THREAD

**Issue by YAFU** [kritiksoman/GIMP-ML#22]
Hi.
Currently plugins autodetect CUDA and they do not allow us to choose to work with CPU. The problem is that plugins make excessive use of vRAM, and most of them fail with out of memory problems even with small images (400x400px) on 4GB vRAM card. Some of them like super-resolution plugin return an error message when out of memory. But other plugins like "deep-denoising" don't return an error message but they don't work unless you are working with very small images.
Thank you.

**Comment by kritiksoman** [comment]
check now

**Comment by YAFU** [comment]
> check now

Thank you very much. CPU works in most plugins. But apparently deep-denoising plugin is still trying to use GPU no matter I choose to force CPU (I get CUDA error)

**Comment by kritiksoman** [comment]
check now

**Comment by YAFU** [comment]
Thanks, it works.
