### ISSUE TITLE
Plug-in crashed: "super_resolution.py"

### ISSUE THREAD

**Issue by cfalonso** [kritiksoman/GIMP-ML#26]
**Describe the bug**
In Ubuntu 20.04 (64 bit) with 8 Gb RAM the plug-in crashes with images around 1000x1000 and higher (it works fine for images around 400x400)

**To Reproduce**
Having a simple image (pictures or even cartoon images) and applying Super Resolution, setting Force CPU to Yes or No, the result is the same.
I get 2 error boxes, one saying that the plug-in crashed, and another one saying "Unable tu run GimpPdbProgress callback. The corresponding plug-in may have crashed"

**Screenshots**
![Screenshot from 2020-09-27 12-02-10](https://user-images.githubusercontent.com/9625888/94369767-ba54c700-00b9-11eb-957e-d291254dcd2f.png)

**Desktop (please complete the following information):**
 - OS Version: Ubuntu 20.04 (64 bit) - VMWare image
 - GIMP Version: 2.10.20

**Comment by kritiksoman** [comment]
check now

**Comment by cfalonso** [comment]
It works great!!! Thank you!!!
