### ISSUE TITLE
Weight Update issue

### ISSUE THREAD

**Issue by Kassiusklay007** [kritiksoman/GIMP-ML#27]
Hello,

I'm installing GIMP-ML with the installation instructions.

I've downloaded the GIT, add gimp-plugins folder in the preferences and restarted GIMP.

Now, running the Weights Update (Layer > GIMP-ML > Update...), clicking on OK (with the selection Update Weights > Yes), I get the following error on GIMP python console :

Traceback (most recent call last):
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 740, in res
ponse
    dialog.res = run_script(params)
  File "C:\Program Files\GIMP 2\lib\gimp\2.0\python/gimpfu.py", line 361, in run
_script
    return apply(function, params)
  File "C:\Program Files\GIMP 2\share\gimp\2.0\scripts\gimp-plugins\update.py",
line 25, in update
    syncWeights.syncGit(baseLoc)
  File "C:\Program Files\GIMP 2\share\gimp\2.0\scripts\gimp-plugins/syncWeights.
py", line 57, in syncGit
    if os.path.samefile(src_file, dst_file):
AttributeError: 'module' object has no attribute 'samefile'

The status in the update window is stucked on "Downloading plugins (~0.5MB)..."

Any idea?

**Comment by Kassiusklay007** [comment]
Screenshot :

![image](https://user-images.githubusercontent.com/39810228/94909717-e13d3f80-04a3-11eb-9b46-e3ffdc5e2822.png)

**Comment by kritiksoman** [comment]
Which OS are you using ?

**Comment by Kassiusklay007** [comment]
Windows, probably not supported

**Comment by kritiksoman** [comment]
yes
