### ISSUE TITLE
Problema con la instalacion

### ISSUE THREAD

**Issue by Cybermannu** [kritiksoman/GIMP-ML#28]
Tengo windows 10 de 64 bits, y Gimp 2.10, al intentar instalar me sale este mensaje ¿hice algo mal?
![image](https://user-images.githubusercontent.com/73871971/97955211-ac0e6080-1d73-11eb-984c-061aac7cf71f.png)

**Comment by kritiksoman** [comment]
Windows no es compatible actualmente.
