### ISSUE TITLE
Slomo between a pair of images

### ISSUE THREAD

**Issue by hzwer** [kritiksoman/GIMP-ML#29]
We have proposed an efficient frame interpolation algorithm and would like to know if there is a chance to be integrated into this software.
https://github.com/hzwer/arXiv2020-RIFE

**Comment by kritiksoman** [comment]
sure, i'll try to include it.

**Comment by valgur** [comment]
If you're taking requests, would you be willing to consider integrating https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life also?

**Comment by kritiksoman** [comment]
@valgur ok @hzwer done

**Comment by nigh8w0lf** [comment]
@kritiksoman some of these models in this projects might be good targets for Inclusion as well :)
https://github.com/xinntao/BasicSR
