### ISSUE TITLE
No menu entry for GIMP-ML on Debian 10

### ISSUE THREAD

**Issue by zevilz** [kritiksoman/GIMP-ML#3]
Steps:
1. Cloned repo.
2. Added gimp-plugins to `Preferences -> Folders -> Plug-ins` and close GIMP.
3. Downloaded weights.zip and save it in gimp-plugins folder.
4. Runned:
```bash
bash moveWeights.sh
bash installGimpML-ubuntu.sh
```

I have no errors during scripts run. But no menu entry in GIMP menu like in screenshot in readme.

Debian 10
GIMP v2.10.8

**Comment by MARDAScience** [comment]
I have the same issue on ubuntu 19.10, gimp version 2.10.8

I also tried copying the scripts (and folders, weights, etc) to ~/.config/GIMP/2.10/plug-ins

**Comment by AstraQuinn** [comment]
Having this same issue on focal fossa using GIMP 2.10.18...

**Comment by bedna-KU** [comment]
Here is this issue described [-> #2](https://github.com/kritiksoman/GIMP-ML/issues/2)

**Comment by yupasik** [comment]
Same thing on MacBook Pro 10.15.4

**Comment by Drohne1** [comment]
I have the same issue on Mint 19 Tara 64-bit, gimp version 2.10.14

**Comment by nortikin** [comment]
also me

**Comment by germanzhu** [comment]
sudo apt install gimp-python

cd gimp-plugins
chmod -x *
chmod +x *.py

restart gimp

**Comment by NISH1001** [comment]
I have the same problem. I tried the steps mentioned. Managed the permissions too. However, cannot see the menu. Is there any way to debug it during gimp startup?

**Comment by zevilz** [comment]
> sudo apt install gimp-python
> 
> cd gimp-plugins
> chmod -x *
> chmod +x *.py
> 
> restart gimp

It worked for me. Thanks!

**Comment by freemsk1** [comment]
Same issue, Mint 19.3, GIMP 2.10.18. The above mentioned solution did not help (((

**Comment by NISH1001** [comment]
> Same issue, Mint 19.3, GIMP 2.10.18. The above-mentioned solution did not help (((

I was able to run. Turned out there were conflicts between conda and virtual env created from the installation script. So, I had a **hacky** way to run the scripts. But then the models barely run in my machine like any other DL models...

**Comment by nortikin** [comment]
installing gimp-python helped me
