### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by ngonthier** [kritiksoman/GIMP-ML#4]
Hi,

Python 2.7 is no more maintained. You should convert your project in Python 3.

Best,

**Comment by kritiksoman** [comment]
Yes, will do.

**Comment by joemarshall** [comment]
It might be possible to convert the backend machine learning stuff to python 3, then run that bit with rpyc, to allow it to work on 2.10 but with the current versions of libraries and modern python.

It would a) potentially simplify install (you could just bundle the backend server as a py2exe.) b) mean windows support would be possible as torch is python 3 only, and c) mean that example code from recent research could be used without the effort of back porting to 2.7.

I might give this a go to see how hard it would be, as I would like the plugin on Windows.

**Comment by joemarshall** [comment]
Scratch that, rpyc is broken between 2.7 and 3 right now, easier solution is to just pipe the image data into a python 3 process, and pipe progress and results back. Is pretty trivial stuff, just reading from stdin in the backend and writing to a subprocess pipe in frontend. This would mean development on the gimp 3 plugin frontend could be completely separate to the plugins themselves, so that work wouldn't break 2.10 compatibility before 3 final comes out.

It would also give the potential for the plugins to be used in other apps too, kind of like ffmpeg is used in many things.

**Comment by PatrickWauters** [comment]
Hello! Thank you for providing these plugins. I'm using Gimp 2.10.18 on Ubuntu 20.04 (installed with apt). I'm eager to try them out however can't get the plugins to work. From gimp --verbose --console-messages

_Querying plug-in: '/home/user/Gimp/GIMP-ML/gimp-plugins/super_resolution.py'
GIMP-Error: Unable to run plug-in "super_resolution.py"
(/home/user/Gimp/GIMP-ML/gimp-plugins/super_resolution.py)

Failed to execute child process “/home/user/Gimp/GIMP-ML/gimp-plugins/super_resolution.py” (Exec format error)_

Is this a clash between python2 and python3 as they are both on my system? Any pointers on how to fix this?

BR

**Comment by prampey** [comment]
Even with python2.7 I get the same error,
```
Parsing '/home/prudhvirampey/.config/GIMP/2.10/pluginrc'
Querying plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/super_resolution.py'
GIMP-Error: Unable to run plug-in "super_resolution.py"
(/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/super_resolution.py)

Failed to execute child process “/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/super_resolution.py” (Exec format error)

Querying plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/monodepth.py'
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/monodepth.py'
Querying plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/invert.py'
gimp: LibGimpBase-WARNING: gimp: gimp_wire_read(): error
Terminating plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/invert.py'
Querying plug-in: '/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/faceparse.py'
GIMP-Error: Unable to run plug-in "faceparse.py"
(/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/faceparse.py)

Failed to execute child process “/home/prudhvirampey/Documents/GIMP-ML/gimp-plugins/faceparse.py” (Exec format error)
```
I think this might not be python version related.

**Comment by frumble** [comment]
I have described the same problem [here](https://github.com/kritiksoman/GIMP-ML/issues/24).
Might it be a platform-specific bug? Does the plugin make use of any Darwin binaries which naturally won’t work on Linux systems?

**Comment by kritiksoman** [comment]
We have started development using python 3.
https://github.com/kritiksoman/GIMP-ML/tree/GIMP3-ML
