### ISSUE TITLE
GIMP3-ML installation does not work

### ISSUE THREAD

**Issue by muziker** [kritiksoman/GIMP-ML#40]
**GIMP3-ML installation does not work**
I followed the installation procedure for the GIMP3-ML branch, and GIMP 2.10.18 does not have any changes or additional plugins. There doesn't seem to be any gimp-plugins folder generated using the install.bat file

**To Reproduce**
1. Follow the GIMP3-ML install instructions
2. Cannot find the gimp-plugins folder for GIMP3-ML

GIMP version 2.10.18
ubuntu

**Comment by kritiksoman** [comment]
the gimp3-ml branch is for gimp 2.99. (https://github.com/kritiksoman/GIMP-ML/tree/GIMP3-ML)
the master branch is for gimp 2.10. (https://github.com/kritiksoman/GIMP-ML)
both branches have different installation steps.

**Comment by muziker** [comment]
Thanks ! Yes i see the installation now.
