### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ryx2** [kritiksoman/GIMP-ML#6]
After following the install instructions, after opening gimp (same when running sudo gimp) on ubuntu:

`gimp screenshot.png 
Gtk-Message: 16:31:03.205: Failed to load module "canberra-gtk-module"

(gimp:4087): GLib-GObject-WARNING **: 16:31:03.210: g_object_set_is_valid_property: object class 'GeglConfig' has no property named 'cache-size'
GIMP-Error: Unable to run plug-in "DeblurGANv2"
(/home/raymond/GIMP-ML/gimp-plugins/DeblurGANv2)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/DeblurGANv2” (Permission denied)

GIMP-Error: Unable to run plug-in "__MACOSX"
(/home/raymond/GIMP-ML/gimp-plugins/__MACOSX)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/__MACOSX” (Permission denied)

GIMP-Error: Unable to run plug-in "pytorch-SRResNet"
(/home/raymond/GIMP-ML/gimp-plugins/pytorch-SRResNet)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/pytorch-SRResNet” (Permission denied)

GIMP-Error: Unable to run plug-in "mkdir"
(/home/raymond/GIMP-ML/gimp-plugins/mkdir)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/mkdir” (Permission denied)

GIMP-Error: Unable to run plug-in "gimpenv"
(/home/raymond/GIMP-ML/gimp-plugins/gimpenv)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/gimpenv” (Permission denied)

GIMP-Error: Unable to run plug-in "monodepth2"
(/home/raymond/GIMP-ML/gimp-plugins/monodepth2)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/monodepth2” (Permission denied)

GIMP-Error: Unable to run plug-in "face-parsing.PyTorch"
(/home/raymond/GIMP-ML/gimp-plugins/face-parsing.PyTorch)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/face-parsing.PyTorch” (Permission denied)

GIMP-Error: Unable to run plug-in "neural-colorization"
(/home/raymond/GIMP-ML/gimp-plugins/neural-colorization)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/neural-colorization” (Permission denied)

/home/raymond/GIMP-ML/gimp-plugins/deeplabv3: 1: /home/raymond/GIMP-ML/gimp-plugins/deeplabv3: ��: not found
/home/raymond/GIMP-ML/gimp-plugins/deeplabv3: 2: /home/raymond/GIMP-ML/gimp-plugins/deeplabv3: Syntax error: "(" unexpected

(gimp:4087): LibGimpBase-WARNING **: 16:31:03.581: gimp: gimp_wire_read(): error
GIMP-Error: Unable to run plug-in "CelebAMask-HQ"
(/home/raymond/GIMP-ML/gimp-plugins/CelebAMask-HQ)

Failed to execute child process “/home/raymond/GIMP-ML/gimp-plugins/CelebAMask-HQ” (Permission denied)`

**Comment by valgur** [comment]
This seems like a harmless GIMP bug to me. GIMP uses the executable permission bit to find plugin scripts and executables and then tries to load or execute them to get the necessary plugin metadata. It however applies the same logic to directories with an executable bit set (which is perfectly normal) for some inexplicable reason as well.
